/* tslint:disable */
/* eslint-disable */
/**
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Balance,
    BalanceFromJSON,
    BalanceToJSON,
} from '../models/Balance';

/**
 * 
 */
export class BalanceApi extends runtime.BaseAPI {

    /**
     * Creates request options for getBalance without sending the request
     */
    async getBalanceRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Signature"] = await this.configuration.apiKey("X-Signature"); // RequestSignature authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Identity"] = await this.configuration.apiKey("X-Identity"); // ProjectIdentity authentication
        }


        let urlPath = `/balance`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Возвращает текущий баланс проекта.
     * Получить баланс
     */
    async getBalanceRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Balance>> {
        const requestOptions = await this.getBalanceRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BalanceFromJSON(jsonValue));
    }

    /**
     * Возвращает текущий баланс проекта.
     * Получить баланс
     */
    async getBalance(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Balance> {
        const response = await this.getBalanceRaw(initOverrides);
        return await response.value();
    }

}
