/* tslint:disable */
/* eslint-disable */
/**
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PaymentDetails,
    PaymentDetailsFromJSON,
    PaymentDetailsToJSON,
} from '../models/PaymentDetails';
import {
    type PaymentList,
    PaymentListFromJSON,
    PaymentListToJSON,
} from '../models/PaymentList';

export interface GetPaymentRequest {
    /**
     * 
     */
    paymentId: string;
}

export interface ListPaymentsRequest {
    /**
     * Идентификатор заказа в системе мерчанта.
     */
    orderId?: string;
    /**
     * 
     */
    status?: Array<ListPaymentsStatusEnum>;
    /**
     * 
     */
    paymentMethod?: ListPaymentsPaymentMethodEnum;
    /**
     * Не больше amountTo, если он передан.
     */
    amountFrom?: number;
    /**
     * Не меньше amountFrom, если он передан.
     */
    amountTo?: number;
    /**
     * Не позже createdTo, если он передан.
     */
    createdFrom?: Date;
    /**
     * Не раньше createdFrom, если он передан.
     */
    createdTo?: Date;
    /**
     * 
     */
    sort?: ListPaymentsSortEnum;
    /**
     * 
     */
    sortDirection?: ListPaymentsSortDirectionEnum;
    /**
     * Непрозрачный курсор из предыдущего ответа. Используйте только с теми же фильтрами и сортировкой.
     */
    cursor?: string;
    /**
     * Количество записей в ответе.
     */
    limit?: number;
}

/**
 * 
 */
export class PaymentsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getPayment without sending the request
     */
    async getPaymentRequestOpts(requestParameters: GetPaymentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['paymentId'] == null) {
            throw new runtime.RequiredError(
                'paymentId',
                'Required parameter "paymentId" was null or undefined when calling getPayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Signature"] = await this.configuration.apiKey("X-Signature"); // RequestSignature authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Identity"] = await this.configuration.apiKey("X-Identity"); // ProjectIdentity authentication
        }


        let urlPath = `/payments/{paymentId}`;
        urlPath = urlPath.replace('{paymentId}', encodeURIComponent(String(requestParameters['paymentId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Получить платёж
     */
    async getPaymentRaw(requestParameters: GetPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentDetails>> {
        const requestOptions = await this.getPaymentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentDetailsFromJSON(jsonValue));
    }

    /**
     * Получить платёж
     */
    async getPayment(requestParameters: GetPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentDetails> {
        const response = await this.getPaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPayments without sending the request
     */
    async listPaymentsRequestOpts(requestParameters: ListPaymentsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['orderId'] != null) {
            queryParameters['orderId'] = requestParameters['orderId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['paymentMethod'] != null) {
            queryParameters['paymentMethod'] = requestParameters['paymentMethod'];
        }

        if (requestParameters['amountFrom'] != null) {
            queryParameters['amountFrom'] = requestParameters['amountFrom'];
        }

        if (requestParameters['amountTo'] != null) {
            queryParameters['amountTo'] = requestParameters['amountTo'];
        }

        if (requestParameters['createdFrom'] != null) {
            queryParameters['createdFrom'] = runtime.serializeDateTime(requestParameters['createdFrom'] as any);
        }

        if (requestParameters['createdTo'] != null) {
            queryParameters['createdTo'] = runtime.serializeDateTime(requestParameters['createdTo'] as any);
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['sortDirection'] != null) {
            queryParameters['sortDirection'] = requestParameters['sortDirection'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Signature"] = await this.configuration.apiKey("X-Signature"); // RequestSignature authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Identity"] = await this.configuration.apiKey("X-Identity"); // ProjectIdentity authentication
        }


        let urlPath = `/payments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Возвращает список платежей проекта.
     * Найти платежи
     */
    async listPaymentsRaw(requestParameters: ListPaymentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentList>> {
        const requestOptions = await this.listPaymentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentListFromJSON(jsonValue));
    }

    /**
     * Возвращает список платежей проекта.
     * Найти платежи
     */
    async listPayments(requestParameters: ListPaymentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentList> {
        const response = await this.listPaymentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListPaymentsStatusEnum = {
    Pending: 'pending',
    Succeeded: 'succeeded',
    Cancelled: 'cancelled',
    Chargebacked: 'chargebacked',
    Refunded: 'refunded',
} as const;
export type ListPaymentsStatusEnum = typeof ListPaymentsStatusEnum[keyof typeof ListPaymentsStatusEnum];
/**
 * @export
 */
export const ListPaymentsPaymentMethodEnum = {
    Sbp: 'sbp',
    Tpay: 'tpay',
} as const;
export type ListPaymentsPaymentMethodEnum = typeof ListPaymentsPaymentMethodEnum[keyof typeof ListPaymentsPaymentMethodEnum];
/**
 * @export
 */
export const ListPaymentsSortEnum = {
    CreatedAt: 'createdAt',
    Amount: 'amount',
} as const;
export type ListPaymentsSortEnum = typeof ListPaymentsSortEnum[keyof typeof ListPaymentsSortEnum];
/**
 * @export
 */
export const ListPaymentsSortDirectionEnum = {
    Asc: 'asc',
    Desc: 'desc',
} as const;
export type ListPaymentsSortDirectionEnum = typeof ListPaymentsSortDirectionEnum[keyof typeof ListPaymentsSortDirectionEnum];
