/* tslint:disable */
/* eslint-disable */
/**
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateSbpPaymentRequest,
    CreateSbpPaymentRequestFromJSON,
    CreateSbpPaymentRequestToJSON,
} from '../models/CreateSbpPaymentRequest';
import {
    type CreateTpayPaymentRequest,
    CreateTpayPaymentRequestFromJSON,
    CreateTpayPaymentRequestToJSON,
} from '../models/CreateTpayPaymentRequest';
import {
    type CreatedPayment,
    CreatedPaymentFromJSON,
    CreatedPaymentToJSON,
} from '../models/CreatedPayment';
import {
    type Payment,
    PaymentFromJSON,
    PaymentToJSON,
} from '../models/Payment';

export interface CreateSbpPaymentOperationRequest {
    /**
     * 
     */
    createSbpPaymentRequest: CreateSbpPaymentRequest;
}

export interface CreateTpayPaymentOperationRequest {
    /**
     * 
     */
    createTpayPaymentRequest: CreateTpayPaymentRequest;
}

/**
 * 
 */
export class PaymentApi extends runtime.BaseAPI {

    /**
     * Creates request options for createSbpPayment without sending the request
     */
    async createSbpPaymentRequestOpts(requestParameters: CreateSbpPaymentOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createSbpPaymentRequest'] == null) {
            throw new runtime.RequiredError(
                'createSbpPaymentRequest',
                'Required parameter "createSbpPaymentRequest" was null or undefined when calling createSbpPayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Signature"] = await this.configuration.apiKey("X-Signature"); // RequestSignature authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Identity"] = await this.configuration.apiKey("X-Identity"); // ProjectIdentity authentication
        }


        let urlPath = `/payments/sbp`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSbpPaymentRequestToJSON(requestParameters['createSbpPaymentRequest']),
        };
    }

    /**
     * Создать платёж по СБП
     */
    async createSbpPaymentRaw(requestParameters: CreateSbpPaymentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Payment>> {
        const requestOptions = await this.createSbpPaymentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentFromJSON(jsonValue));
    }

    /**
     * Создать платёж по СБП
     */
    async createSbpPayment(requestParameters: CreateSbpPaymentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Payment> {
        const response = await this.createSbpPaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createTpayPayment without sending the request
     */
    async createTpayPaymentRequestOpts(requestParameters: CreateTpayPaymentOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createTpayPaymentRequest'] == null) {
            throw new runtime.RequiredError(
                'createTpayPaymentRequest',
                'Required parameter "createTpayPaymentRequest" was null or undefined when calling createTpayPayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Signature"] = await this.configuration.apiKey("X-Signature"); // RequestSignature authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Identity"] = await this.configuration.apiKey("X-Identity"); // ProjectIdentity authentication
        }


        let urlPath = `/payments/tpay`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTpayPaymentRequestToJSON(requestParameters['createTpayPaymentRequest']),
        };
    }

    /**
     * Создать платёж через T-Pay
     */
    async createTpayPaymentRaw(requestParameters: CreateTpayPaymentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Payment>> {
        const requestOptions = await this.createTpayPaymentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentFromJSON(jsonValue));
    }

    /**
     * Создать платёж через T-Pay
     */
    async createTpayPayment(requestParameters: CreateTpayPaymentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Payment> {
        const response = await this.createTpayPaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
