/* tslint:disable */
/* eslint-disable */
/**
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateRefundRequest,
    CreateRefundRequestFromJSON,
    CreateRefundRequestToJSON,
} from '../models/CreateRefundRequest';
import {
    type PendingRefund,
    PendingRefundFromJSON,
    PendingRefundToJSON,
} from '../models/PendingRefund';
import {
    type Refund,
    RefundFromJSON,
    RefundToJSON,
} from '../models/Refund';

export interface CreatePaymentRefundRequest {
    /**
     * 
     */
    paymentId: string;
    /**
     * 
     */
    createRefundRequest: CreateRefundRequest;
}

export interface GetPaymentRefundRequest {
    /**
     * 
     */
    paymentId: string;
}

/**
 * 
 */
export class RefundsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createPaymentRefund without sending the request
     */
    async createPaymentRefundRequestOpts(requestParameters: CreatePaymentRefundRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['paymentId'] == null) {
            throw new runtime.RequiredError(
                'paymentId',
                'Required parameter "paymentId" was null or undefined when calling createPaymentRefund().'
            );
        }

        if (requestParameters['createRefundRequest'] == null) {
            throw new runtime.RequiredError(
                'createRefundRequest',
                'Required parameter "createRefundRequest" was null or undefined when calling createPaymentRefund().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Signature"] = await this.configuration.apiKey("X-Signature"); // RequestSignature authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Identity"] = await this.configuration.apiKey("X-Identity"); // ProjectIdentity authentication
        }


        let urlPath = `/payments/{paymentId}/refund`;
        urlPath = urlPath.replace('{paymentId}', encodeURIComponent(String(requestParameters['paymentId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRefundRequestToJSON(requestParameters['createRefundRequest']),
        };
    }

    /**
     * Создать возврат
     */
    async createPaymentRefundRaw(requestParameters: CreatePaymentRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Refund>> {
        const requestOptions = await this.createPaymentRefundRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RefundFromJSON(jsonValue));
    }

    /**
     * Создать возврат
     */
    async createPaymentRefund(requestParameters: CreatePaymentRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Refund> {
        const response = await this.createPaymentRefundRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPaymentRefund without sending the request
     */
    async getPaymentRefundRequestOpts(requestParameters: GetPaymentRefundRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['paymentId'] == null) {
            throw new runtime.RequiredError(
                'paymentId',
                'Required parameter "paymentId" was null or undefined when calling getPaymentRefund().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Signature"] = await this.configuration.apiKey("X-Signature"); // RequestSignature authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Identity"] = await this.configuration.apiKey("X-Identity"); // ProjectIdentity authentication
        }


        let urlPath = `/payments/{paymentId}/refund`;
        urlPath = urlPath.replace('{paymentId}', encodeURIComponent(String(requestParameters['paymentId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Получить возврат
     */
    async getPaymentRefundRaw(requestParameters: GetPaymentRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Refund>> {
        const requestOptions = await this.getPaymentRefundRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RefundFromJSON(jsonValue));
    }

    /**
     * Получить возврат
     */
    async getPaymentRefund(requestParameters: GetPaymentRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Refund> {
        const response = await this.getPaymentRefundRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
