/* tslint:disable */
/* eslint-disable */
/**
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Balance
 */
export interface Balance {
    /**
     * 
     */
    projectId: string;
    /**
     * 
     */
    balance: number;
    /**
     * 
     */
    currency: BalanceCurrencyEnum;
}


/**
 * @export
 */
export const BalanceCurrencyEnum = {
    Rub: 'RUB',
} as const;
export type BalanceCurrencyEnum = typeof BalanceCurrencyEnum[keyof typeof BalanceCurrencyEnum];


/**
 * Check if a given object implements the Balance interface.
 */
export function instanceOfBalance(value: object): value is Balance {
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (value['currency'] !== 'RUB') return false;
    
    return true;
}

export function BalanceFromJSON(json: any): Balance {
    return BalanceFromJSONTyped(json, false);
}

export function BalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Balance {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['projectId'],
        'balance': json['balance'],
        'currency': json['currency'],
    };
}

export function BalanceToJSON(json: any): Balance {
    return BalanceToJSONTyped(json, false);
}

export function BalanceToJSONTyped(value?: Balance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projectId': value['projectId'],
        'balance': value['balance'],
        'currency': value['currency'],
    };
}

