/* tslint:disable */
/* eslint-disable */
/**
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRefundRequest
 */
export interface CreateRefundRequest {
    /**
     * Сумма в копейках.
     */
    amount?: number;
    /**
     * 
     */
    reason?: string;
}

/**
 * Check if a given object implements the CreateRefundRequest interface.
 */
export function instanceOfCreateRefundRequest(value: object): value is CreateRefundRequest {
    return true;
}

export function CreateRefundRequestFromJSON(json: any): CreateRefundRequest {
    return CreateRefundRequestFromJSONTyped(json, false);
}

export function CreateRefundRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRefundRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function CreateRefundRequestToJSON(json: any): CreateRefundRequest {
    return CreateRefundRequestToJSONTyped(json, false);
}

export function CreateRefundRequestToJSONTyped(value?: CreateRefundRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'reason': value['reason'],
    };
}

