/* tslint:disable */
/* eslint-disable */
/**
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface CreatedPayment
 */
export interface CreatedPayment {
    /**
     * 
     */
    paymentId: string;
    /**
     * 
     */
    orderId: string;
    /**
     * Сумма в копейках.
     */
    amount: number;
    /**
     * 
     */
    currency: CreatedPaymentCurrencyEnum;
    /**
     * 
     */
    description?: string;
    /**
     * 
     */
    paymentMethod: CreatedPaymentPaymentMethodEnum;
    /**
     * 
     */
    status: CreatedPaymentStatusEnum;
    /**
     * 
     */
    paymentUrl: string;
    /**
     * 
     */
    expiresAt: Date;
    /**
     * 
     */
    failureCode?: string;
    /**
     * 
     */
    failureMessage?: string;
    /**
     * 
     */
    completedAt?: Date;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const CreatedPaymentCurrencyEnum = {
    Rub: 'RUB',
} as const;
export type CreatedPaymentCurrencyEnum = typeof CreatedPaymentCurrencyEnum[keyof typeof CreatedPaymentCurrencyEnum];

/**
 * @export
 */
export const CreatedPaymentPaymentMethodEnum = {
    Sbp: 'sbp',
    Tpay: 'tpay',
} as const;
export type CreatedPaymentPaymentMethodEnum = typeof CreatedPaymentPaymentMethodEnum[keyof typeof CreatedPaymentPaymentMethodEnum];

/**
 * @export
 */
export const CreatedPaymentStatusEnum = {
    Pending: 'pending',
    Succeeded: 'succeeded',
    Cancelled: 'cancelled',
    Chargebacked: 'chargebacked',
    Refunded: 'refunded',
} as const;
export type CreatedPaymentStatusEnum = typeof CreatedPaymentStatusEnum[keyof typeof CreatedPaymentStatusEnum];


/**
 * Check if a given object implements the CreatedPayment interface.
 */
export function instanceOfCreatedPayment(value: object): value is CreatedPayment {
    if (!('paymentId' in value) || value['paymentId'] === undefined) return false;
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (value['currency'] !== 'RUB') return false;
    
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('paymentUrl' in value) || value['paymentUrl'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CreatedPaymentFromJSON(json: any): CreatedPayment {
    return CreatedPaymentFromJSONTyped(json, false);
}

export function CreatedPaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatedPayment {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentId': json['paymentId'],
        'orderId': json['orderId'],
        'amount': json['amount'],
        'currency': json['currency'],
        'description': json['description'] == null ? undefined : json['description'],
        'paymentMethod': json['paymentMethod'],
        'status': json['status'],
        'paymentUrl': json['paymentUrl'],
        'expiresAt': (json['expiresAt'] == null ? json['expiresAt'] : parseDateTime(json['expiresAt'])),
        'failureCode': json['failureCode'] == null ? undefined : json['failureCode'],
        'failureMessage': json['failureMessage'] == null ? undefined : json['failureMessage'],
        'completedAt': json['completedAt'] == null ? undefined : (parseDateTime(json['completedAt'])),
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'updatedAt': (json['updatedAt'] == null ? json['updatedAt'] : parseDateTime(json['updatedAt'])),
    };
}

export function CreatedPaymentToJSON(json: any): CreatedPayment {
    return CreatedPaymentToJSONTyped(json, false);
}

export function CreatedPaymentToJSONTyped(value?: CreatedPayment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paymentId': value['paymentId'],
        'orderId': value['orderId'],
        'amount': value['amount'],
        'currency': value['currency'],
        'description': value['description'],
        'paymentMethod': value['paymentMethod'],
        'status': value['status'],
        'paymentUrl': value['paymentUrl'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : serializeDateTime(value['expiresAt']),
        'failureCode': value['failureCode'],
        'failureMessage': value['failureMessage'],
        'completedAt': value['completedAt'] == null ? value['completedAt'] : serializeDateTime(value['completedAt']),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}

