/* tslint:disable */
/* eslint-disable */
/**
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TpayDeviceData } from './TpayDeviceData';
import {
    TpayDeviceDataFromJSON,
    TpayDeviceDataFromJSONTyped,
    TpayDeviceDataToJSON,
    TpayDeviceDataToJSONTyped,
} from './TpayDeviceData';

/**
 * 
 * @export
 * @interface CreateTpayPaymentRequest
 */
export interface CreateTpayPaymentRequest {
    /**
     * Идентификатор заказа в системе мерчанта.
     */
    orderId: string;
    /**
     * Сумма в копейках.
     */
    amount: number;
    /**
     * 
     */
    currency: CreateTpayPaymentRequestCurrencyEnum;
    /**
     * 
     */
    description?: string;
    /**
     * IP-адрес плательщика: IPv4 или IPv6.
     */
    ip: string;
    /**
     * HTTPS-адрес уведомлений.
     */
    callbackUrl: string;
    /**
     * HTTPS-адрес для успешной оплаты.
     */
    successUrl: string;
    /**
     * HTTPS-адрес для отменённой оплаты.
     */
    failedUrl: string;
    /**
     * 
     */
    deviceData: TpayDeviceData;
}


/**
 * @export
 */
export const CreateTpayPaymentRequestCurrencyEnum = {
    Rub: 'RUB',
} as const;
export type CreateTpayPaymentRequestCurrencyEnum = typeof CreateTpayPaymentRequestCurrencyEnum[keyof typeof CreateTpayPaymentRequestCurrencyEnum];


/**
 * Check if a given object implements the CreateTpayPaymentRequest interface.
 */
export function instanceOfCreateTpayPaymentRequest(value: object): value is CreateTpayPaymentRequest {
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (value['currency'] !== 'RUB') return false;
    
    if (!('ip' in value) || value['ip'] === undefined) return false;
    if (!('callbackUrl' in value) || value['callbackUrl'] === undefined) return false;
    if (!('successUrl' in value) || value['successUrl'] === undefined) return false;
    if (!('failedUrl' in value) || value['failedUrl'] === undefined) return false;
    if (!('deviceData' in value) || value['deviceData'] === undefined) return false;
    return true;
}

export function CreateTpayPaymentRequestFromJSON(json: any): CreateTpayPaymentRequest {
    return CreateTpayPaymentRequestFromJSONTyped(json, false);
}

export function CreateTpayPaymentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTpayPaymentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'],
        'amount': json['amount'],
        'currency': json['currency'],
        'description': json['description'] == null ? undefined : json['description'],
        'ip': json['ip'],
        'callbackUrl': json['callbackUrl'],
        'successUrl': json['successUrl'],
        'failedUrl': json['failedUrl'],
        'deviceData': TpayDeviceDataFromJSON(json['deviceData']),
    };
}

export function CreateTpayPaymentRequestToJSON(json: any): CreateTpayPaymentRequest {
    return CreateTpayPaymentRequestToJSONTyped(json, false);
}

export function CreateTpayPaymentRequestToJSONTyped(value?: CreateTpayPaymentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
        'amount': value['amount'],
        'currency': value['currency'],
        'description': value['description'],
        'ip': value['ip'],
        'callbackUrl': value['callbackUrl'],
        'successUrl': value['successUrl'],
        'failedUrl': value['failedUrl'],
        'deviceData': TpayDeviceDataToJSON(value['deviceData']),
    };
}

