/* tslint:disable */
/* eslint-disable */
/**
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceData
 */
export interface DeviceData {
    /**
     * 
     */
    platformType?: DeviceDataPlatformTypeEnum;
    /**
     * 
     */
    os?: string;
    /**
     * 
     */
    browser?: string;
    /**
     * 
     */
    language?: string;
    /**
     * 
     */
    timezoneName?: string;
    /**
     * 
     */
    userAgent?: string;
}


/**
 * @export
 */
export const DeviceDataPlatformTypeEnum = {
    Mobile: 'mobile',
    Desktop: 'desktop',
} as const;
export type DeviceDataPlatformTypeEnum = typeof DeviceDataPlatformTypeEnum[keyof typeof DeviceDataPlatformTypeEnum];


/**
 * Check if a given object implements the DeviceData interface.
 */
export function instanceOfDeviceData(value: object): value is DeviceData {
    return true;
}

export function DeviceDataFromJSON(json: any): DeviceData {
    return DeviceDataFromJSONTyped(json, false);
}

export function DeviceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceData {
    if (json == null) {
        return json;
    }
    return {
        
        'platformType': json['platformType'] == null ? undefined : json['platformType'],
        'os': json['os'] == null ? undefined : json['os'],
        'browser': json['browser'] == null ? undefined : json['browser'],
        'language': json['language'] == null ? undefined : json['language'],
        'timezoneName': json['timezoneName'] == null ? undefined : json['timezoneName'],
        'userAgent': json['userAgent'] == null ? undefined : json['userAgent'],
    };
}

export function DeviceDataToJSON(json: any): DeviceData {
    return DeviceDataToJSONTyped(json, false);
}

export function DeviceDataToJSONTyped(value?: DeviceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'platformType': value['platformType'],
        'os': value['os'],
        'browser': value['browser'],
        'language': value['language'],
        'timezoneName': value['timezoneName'],
        'userAgent': value['userAgent'],
    };
}

