/* tslint:disable */
/* eslint-disable */
/**
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorErrorDetailsInner } from './ErrorErrorDetailsInner';
import {
    ErrorErrorDetailsInnerFromJSON,
    ErrorErrorDetailsInnerFromJSONTyped,
    ErrorErrorDetailsInnerToJSON,
    ErrorErrorDetailsInnerToJSONTyped,
} from './ErrorErrorDetailsInner';

/**
 * 
 * @export
 * @interface ErrorError
 */
export interface ErrorError {
    /**
     * 
     */
    type: string;
    /**
     * 
     */
    code: string;
    /**
     * 
     */
    message: string;
    /**
     * 
     */
    details?: Array<ErrorErrorDetailsInner>;
    /**
     * 
     */
    requestId: string;
}

/**
 * Check if a given object implements the ErrorError interface.
 */
export function instanceOfErrorError(value: object): value is ErrorError {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function ErrorErrorFromJSON(json: any): ErrorError {
    return ErrorErrorFromJSONTyped(json, false);
}

export function ErrorErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorError {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'code': json['code'],
        'message': json['message'],
        'details': json['details'] == null ? undefined : ((json['details'] as Array<any>).map(ErrorErrorDetailsInnerFromJSON)),
        'requestId': json['requestId'],
    };
}

export function ErrorErrorToJSON(json: any): ErrorError {
    return ErrorErrorToJSONTyped(json, false);
}

export function ErrorErrorToJSONTyped(value?: ErrorError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'code': value['code'],
        'message': value['message'],
        'details': value['details'] == null ? undefined : ((value['details'] as Array<any>).map(ErrorErrorDetailsInnerToJSON)),
        'requestId': value['requestId'],
    };
}

