/* tslint:disable */
/* eslint-disable */
/**
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorErrorDetailsInner
 */
export interface ErrorErrorDetailsInner {
    /**
     * 
     */
    field: string;
    /**
     * 
     */
    code: string;
    /**
     * 
     */
    message: string;
}

/**
 * Check if a given object implements the ErrorErrorDetailsInner interface.
 */
export function instanceOfErrorErrorDetailsInner(value: object): value is ErrorErrorDetailsInner {
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ErrorErrorDetailsInnerFromJSON(json: any): ErrorErrorDetailsInner {
    return ErrorErrorDetailsInnerFromJSONTyped(json, false);
}

export function ErrorErrorDetailsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorErrorDetailsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'],
        'code': json['code'],
        'message': json['message'],
    };
}

export function ErrorErrorDetailsInnerToJSON(json: any): ErrorErrorDetailsInner {
    return ErrorErrorDetailsInnerToJSONTyped(json, false);
}

export function ErrorErrorDetailsInnerToJSONTyped(value?: ErrorErrorDetailsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'code': value['code'],
        'message': value['message'],
    };
}

