/* tslint:disable */
/* eslint-disable */
/**
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { Refund } from './Refund';
import {
    RefundFromJSON,
    RefundFromJSONTyped,
    RefundToJSON,
    RefundToJSONTyped,
} from './Refund';

/**
 * 
 * @export
 * @interface PaymentDetails
 */
export interface PaymentDetails {
    /**
     * 
     */
    paymentId: string;
    /**
     * 
     */
    orderId: string;
    /**
     * Сумма в копейках.
     */
    amount: number;
    /**
     * 
     */
    currency: PaymentDetailsCurrencyEnum;
    /**
     * 
     */
    description?: string;
    /**
     * 
     */
    paymentMethod: PaymentDetailsPaymentMethodEnum;
    /**
     * 
     */
    status: PaymentDetailsStatusEnum;
    /**
     * Адрес оплаты для платежа в статусе pending.
     */
    paymentUrl?: string;
    /**
     * 
     */
    expiresAt?: Date;
    /**
     * 
     */
    failureCode?: string;
    /**
     * 
     */
    failureMessage?: string;
    /**
     * 
     */
    completedAt?: Date;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    updatedAt: Date;
    /**
     * 
     */
    refund?: Refund;
}


/**
 * @export
 */
export const PaymentDetailsCurrencyEnum = {
    Rub: 'RUB',
} as const;
export type PaymentDetailsCurrencyEnum = typeof PaymentDetailsCurrencyEnum[keyof typeof PaymentDetailsCurrencyEnum];

/**
 * @export
 */
export const PaymentDetailsPaymentMethodEnum = {
    Sbp: 'sbp',
    Tpay: 'tpay',
} as const;
export type PaymentDetailsPaymentMethodEnum = typeof PaymentDetailsPaymentMethodEnum[keyof typeof PaymentDetailsPaymentMethodEnum];

/**
 * @export
 */
export const PaymentDetailsStatusEnum = {
    Pending: 'pending',
    Succeeded: 'succeeded',
    Cancelled: 'cancelled',
    Chargebacked: 'chargebacked',
    Refunded: 'refunded',
} as const;
export type PaymentDetailsStatusEnum = typeof PaymentDetailsStatusEnum[keyof typeof PaymentDetailsStatusEnum];


/**
 * Check if a given object implements the PaymentDetails interface.
 */
export function instanceOfPaymentDetails(value: object): value is PaymentDetails {
    if (!('paymentId' in value) || value['paymentId'] === undefined) return false;
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (value['currency'] !== 'RUB') return false;
    
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PaymentDetailsFromJSON(json: any): PaymentDetails {
    return PaymentDetailsFromJSONTyped(json, false);
}

export function PaymentDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentId': json['paymentId'],
        'orderId': json['orderId'],
        'amount': json['amount'],
        'currency': json['currency'],
        'description': json['description'] == null ? undefined : json['description'],
        'paymentMethod': json['paymentMethod'],
        'status': json['status'],
        'paymentUrl': json['paymentUrl'] == null ? undefined : json['paymentUrl'],
        'expiresAt': json['expiresAt'] == null ? undefined : (parseDateTime(json['expiresAt'])),
        'failureCode': json['failureCode'] == null ? undefined : json['failureCode'],
        'failureMessage': json['failureMessage'] == null ? undefined : json['failureMessage'],
        'completedAt': json['completedAt'] == null ? undefined : (parseDateTime(json['completedAt'])),
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'updatedAt': (json['updatedAt'] == null ? json['updatedAt'] : parseDateTime(json['updatedAt'])),
        'refund': json['refund'] == null ? undefined : RefundFromJSON(json['refund']),
    };
}

export function PaymentDetailsToJSON(json: any): PaymentDetails {
    return PaymentDetailsToJSONTyped(json, false);
}

export function PaymentDetailsToJSONTyped(value?: PaymentDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paymentId': value['paymentId'],
        'orderId': value['orderId'],
        'amount': value['amount'],
        'currency': value['currency'],
        'description': value['description'],
        'paymentMethod': value['paymentMethod'],
        'status': value['status'],
        'paymentUrl': value['paymentUrl'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : serializeDateTime(value['expiresAt']),
        'failureCode': value['failureCode'],
        'failureMessage': value['failureMessage'],
        'completedAt': value['completedAt'] == null ? value['completedAt'] : serializeDateTime(value['completedAt']),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
        'refund': RefundToJSON(value['refund']),
    };
}

