/* tslint:disable */
/* eslint-disable */
/**
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Payment } from './Payment';
import {
    PaymentFromJSON,
    PaymentFromJSONTyped,
    PaymentToJSON,
    PaymentToJSONTyped,
} from './Payment';

/**
 * 
 * @export
 * @interface PaymentList
 */
export interface PaymentList {
    /**
     * 
     */
    items: Array<Payment>;
    /**
     * 
     */
    nextCursor: string;
    /**
     * 
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the PaymentList interface.
 */
export function instanceOfPaymentList(value: object): value is PaymentList {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function PaymentListFromJSON(json: any): PaymentList {
    return PaymentListFromJSONTyped(json, false);
}

export function PaymentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PaymentFromJSON)),
        'nextCursor': json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function PaymentListToJSON(json: any): PaymentList {
    return PaymentListToJSONTyped(json, false);
}

export function PaymentListToJSONTyped(value?: PaymentList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(PaymentToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}

