/* tslint:disable */
/* eslint-disable */
/**
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { FinalPayment } from './FinalPayment';
import {
    FinalPaymentFromJSON,
    FinalPaymentFromJSONTyped,
    FinalPaymentToJSON,
    FinalPaymentToJSONTyped,
} from './FinalPayment';

/**
 * 
 * @export
 * @interface PostpaymentWebhookNotification
 */
export interface PostpaymentWebhookNotification {
    /**
     * 
     */
    notificationId: string;
    /**
     * 
     */
    notificationType: PostpaymentWebhookNotificationNotificationTypeEnum;
    /**
     * 
     */
    notificationDate: Date;
    /**
     * 
     */
    payment: FinalPayment;
}


/**
 * @export
 */
export const PostpaymentWebhookNotificationNotificationTypeEnum = {
    Postpayment: 'postpayment',
} as const;
export type PostpaymentWebhookNotificationNotificationTypeEnum = typeof PostpaymentWebhookNotificationNotificationTypeEnum[keyof typeof PostpaymentWebhookNotificationNotificationTypeEnum];


/**
 * Check if a given object implements the PostpaymentWebhookNotification interface.
 */
export function instanceOfPostpaymentWebhookNotification(value: object): value is PostpaymentWebhookNotification {
    if (!('notificationId' in value) || value['notificationId'] === undefined) return false;
    if (!('notificationType' in value) || value['notificationType'] === undefined) return false;
    if (value['notificationType'] !== 'postpayment') return false;
    
    if (!('notificationDate' in value) || value['notificationDate'] === undefined) return false;
    if (!('payment' in value) || value['payment'] === undefined) return false;
    return true;
}

export function PostpaymentWebhookNotificationFromJSON(json: any): PostpaymentWebhookNotification {
    return PostpaymentWebhookNotificationFromJSONTyped(json, false);
}

export function PostpaymentWebhookNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostpaymentWebhookNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'notificationId': json['notificationId'],
        'notificationType': json['notificationType'],
        'notificationDate': (json['notificationDate'] == null ? json['notificationDate'] : parseDateTime(json['notificationDate'])),
        'payment': FinalPaymentFromJSON(json['payment']),
    };
}

export function PostpaymentWebhookNotificationToJSON(json: any): PostpaymentWebhookNotification {
    return PostpaymentWebhookNotificationToJSONTyped(json, false);
}

export function PostpaymentWebhookNotificationToJSONTyped(value?: PostpaymentWebhookNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notificationId': value['notificationId'],
        'notificationType': value['notificationType'],
        'notificationDate': value['notificationDate'] == null ? value['notificationDate'] : serializeDateTime(value['notificationDate']),
        'payment': FinalPaymentToJSON(value['payment']),
    };
}

