/* tslint:disable */
/* eslint-disable */
/**
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { PrepaymentPayment } from './PrepaymentPayment';
import {
    PrepaymentPaymentFromJSON,
    PrepaymentPaymentFromJSONTyped,
    PrepaymentPaymentToJSON,
    PrepaymentPaymentToJSONTyped,
} from './PrepaymentPayment';

/**
 * 
 * @export
 * @interface PrepaymentWebhookNotification
 */
export interface PrepaymentWebhookNotification {
    /**
     * 
     */
    notificationId: string;
    /**
     * 
     */
    notificationType: PrepaymentWebhookNotificationNotificationTypeEnum;
    /**
     * 
     */
    notificationDate: Date;
    /**
     * 
     */
    payment: PrepaymentPayment;
}


/**
 * @export
 */
export const PrepaymentWebhookNotificationNotificationTypeEnum = {
    Prepayment: 'prepayment',
} as const;
export type PrepaymentWebhookNotificationNotificationTypeEnum = typeof PrepaymentWebhookNotificationNotificationTypeEnum[keyof typeof PrepaymentWebhookNotificationNotificationTypeEnum];


/**
 * Check if a given object implements the PrepaymentWebhookNotification interface.
 */
export function instanceOfPrepaymentWebhookNotification(value: object): value is PrepaymentWebhookNotification {
    if (!('notificationId' in value) || value['notificationId'] === undefined) return false;
    if (!('notificationType' in value) || value['notificationType'] === undefined) return false;
    if (value['notificationType'] !== 'prepayment') return false;
    
    if (!('notificationDate' in value) || value['notificationDate'] === undefined) return false;
    if (!('payment' in value) || value['payment'] === undefined) return false;
    return true;
}

export function PrepaymentWebhookNotificationFromJSON(json: any): PrepaymentWebhookNotification {
    return PrepaymentWebhookNotificationFromJSONTyped(json, false);
}

export function PrepaymentWebhookNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrepaymentWebhookNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'notificationId': json['notificationId'],
        'notificationType': json['notificationType'],
        'notificationDate': (json['notificationDate'] == null ? json['notificationDate'] : parseDateTime(json['notificationDate'])),
        'payment': PrepaymentPaymentFromJSON(json['payment']),
    };
}

export function PrepaymentWebhookNotificationToJSON(json: any): PrepaymentWebhookNotification {
    return PrepaymentWebhookNotificationToJSONTyped(json, false);
}

export function PrepaymentWebhookNotificationToJSONTyped(value?: PrepaymentWebhookNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notificationId': value['notificationId'],
        'notificationType': value['notificationType'],
        'notificationDate': value['notificationDate'] == null ? value['notificationDate'] : serializeDateTime(value['notificationDate']),
        'payment': PrepaymentPaymentToJSON(value['payment']),
    };
}

