/* tslint:disable */
/* eslint-disable */
/**
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface PrepaymentPayment
 */
export interface PrepaymentPayment {
    /**
     * 
     */
    paymentId: string;
    /**
     * 
     */
    orderId: string;
    /**
     * Сумма в копейках.
     */
    amount: number;
    /**
     * 
     */
    currency: PrepaymentPaymentCurrencyEnum;
    /**
     * 
     */
    description?: string;
    /**
     * 
     */
    paymentMethod: PrepaymentPaymentPaymentMethodEnum;
    /**
     * 
     */
    status: PrepaymentPaymentStatusEnum;
    /**
     * Адрес оплаты для платежа в статусе pending.
     */
    paymentUrl?: string;
    /**
     * 
     */
    expiresAt?: Date;
    /**
     * 
     */
    failureCode?: string;
    /**
     * 
     */
    failureMessage?: string;
    /**
     * 
     */
    completedAt?: Date;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const PrepaymentPaymentCurrencyEnum = {
    Rub: 'RUB',
} as const;
export type PrepaymentPaymentCurrencyEnum = typeof PrepaymentPaymentCurrencyEnum[keyof typeof PrepaymentPaymentCurrencyEnum];

/**
 * @export
 */
export const PrepaymentPaymentPaymentMethodEnum = {
    Sbp: 'sbp',
    Tpay: 'tpay',
} as const;
export type PrepaymentPaymentPaymentMethodEnum = typeof PrepaymentPaymentPaymentMethodEnum[keyof typeof PrepaymentPaymentPaymentMethodEnum];

/**
 * @export
 */
export const PrepaymentPaymentStatusEnum = {
    Pending: 'pending',
} as const;
export type PrepaymentPaymentStatusEnum = typeof PrepaymentPaymentStatusEnum[keyof typeof PrepaymentPaymentStatusEnum];


/**
 * Check if a given object implements the PrepaymentPayment interface.
 */
export function instanceOfPrepaymentPayment(value: object): value is PrepaymentPayment {
    if (!('paymentId' in value) || value['paymentId'] === undefined) return false;
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (value['currency'] !== 'RUB') return false;
    
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (value['status'] !== 'pending') return false;
    
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PrepaymentPaymentFromJSON(json: any): PrepaymentPayment {
    return PrepaymentPaymentFromJSONTyped(json, false);
}

export function PrepaymentPaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrepaymentPayment {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentId': json['paymentId'],
        'orderId': json['orderId'],
        'amount': json['amount'],
        'currency': json['currency'],
        'description': json['description'] == null ? undefined : json['description'],
        'paymentMethod': json['paymentMethod'],
        'status': json['status'],
        'paymentUrl': json['paymentUrl'] == null ? undefined : json['paymentUrl'],
        'expiresAt': json['expiresAt'] == null ? undefined : (parseDateTime(json['expiresAt'])),
        'failureCode': json['failureCode'] == null ? undefined : json['failureCode'],
        'failureMessage': json['failureMessage'] == null ? undefined : json['failureMessage'],
        'completedAt': json['completedAt'] == null ? undefined : (parseDateTime(json['completedAt'])),
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'updatedAt': (json['updatedAt'] == null ? json['updatedAt'] : parseDateTime(json['updatedAt'])),
    };
}

export function PrepaymentPaymentToJSON(json: any): PrepaymentPayment {
    return PrepaymentPaymentToJSONTyped(json, false);
}

export function PrepaymentPaymentToJSONTyped(value?: PrepaymentPayment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paymentId': value['paymentId'],
        'orderId': value['orderId'],
        'amount': value['amount'],
        'currency': value['currency'],
        'description': value['description'],
        'paymentMethod': value['paymentMethod'],
        'status': value['status'],
        'paymentUrl': value['paymentUrl'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : serializeDateTime(value['expiresAt']),
        'failureCode': value['failureCode'],
        'failureMessage': value['failureMessage'],
        'completedAt': value['completedAt'] == null ? value['completedAt'] : serializeDateTime(value['completedAt']),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}

