/* tslint:disable */
/* eslint-disable */
/**
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface Refund
 */
export interface Refund {
    /**
     * 
     */
    paymentId: string;
    /**
     * Сумма в копейках.
     */
    amount: number;
    /**
     * 
     */
    currency: RefundCurrencyEnum;
    /**
     * 
     */
    status: RefundStatusEnum;
    /**
     * 
     */
    reason?: string;
    /**
     * 
     */
    failureCode?: string;
    /**
     * 
     */
    failureMessage?: string;
    /**
     * 
     */
    acceptedAt?: Date;
    /**
     * 
     */
    declinedAt?: Date;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const RefundCurrencyEnum = {
    Rub: 'RUB',
} as const;
export type RefundCurrencyEnum = typeof RefundCurrencyEnum[keyof typeof RefundCurrencyEnum];

/**
 * @export
 */
export const RefundStatusEnum = {
    Pending: 'pending',
    Accepted: 'accepted',
    Declined: 'declined',
} as const;
export type RefundStatusEnum = typeof RefundStatusEnum[keyof typeof RefundStatusEnum];


/**
 * Check if a given object implements the Refund interface.
 */
export function instanceOfRefund(value: object): value is Refund {
    if (!('paymentId' in value) || value['paymentId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (value['currency'] !== 'RUB') return false;
    
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function RefundFromJSON(json: any): Refund {
    return RefundFromJSONTyped(json, false);
}

export function RefundFromJSONTyped(json: any, ignoreDiscriminator: boolean): Refund {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentId': json['paymentId'],
        'amount': json['amount'],
        'currency': json['currency'],
        'status': json['status'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'failureCode': json['failureCode'] == null ? undefined : json['failureCode'],
        'failureMessage': json['failureMessage'] == null ? undefined : json['failureMessage'],
        'acceptedAt': json['acceptedAt'] == null ? undefined : (parseDateTime(json['acceptedAt'])),
        'declinedAt': json['declinedAt'] == null ? undefined : (parseDateTime(json['declinedAt'])),
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'updatedAt': (json['updatedAt'] == null ? json['updatedAt'] : parseDateTime(json['updatedAt'])),
    };
}

export function RefundToJSON(json: any): Refund {
    return RefundToJSONTyped(json, false);
}

export function RefundToJSONTyped(value?: Refund | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paymentId': value['paymentId'],
        'amount': value['amount'],
        'currency': value['currency'],
        'status': value['status'],
        'reason': value['reason'],
        'failureCode': value['failureCode'],
        'failureMessage': value['failureMessage'],
        'acceptedAt': value['acceptedAt'] == null ? value['acceptedAt'] : serializeDateTime(value['acceptedAt']),
        'declinedAt': value['declinedAt'] == null ? value['declinedAt'] : serializeDateTime(value['declinedAt']),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}

