/* tslint:disable */
/* eslint-disable */
/**
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { FinalRefund } from './FinalRefund';
import {
    FinalRefundFromJSON,
    FinalRefundFromJSONTyped,
    FinalRefundToJSON,
    FinalRefundToJSONTyped,
} from './FinalRefund';

/**
 * 
 * @export
 * @interface RefundWebhookNotification
 */
export interface RefundWebhookNotification {
    /**
     * 
     */
    notificationId: string;
    /**
     * 
     */
    notificationType: RefundWebhookNotificationNotificationTypeEnum;
    /**
     * 
     */
    notificationDate: Date;
    /**
     * 
     */
    paymentId: string;
    /**
     * 
     */
    refund: FinalRefund;
}


/**
 * @export
 */
export const RefundWebhookNotificationNotificationTypeEnum = {
    Refund: 'refund',
} as const;
export type RefundWebhookNotificationNotificationTypeEnum = typeof RefundWebhookNotificationNotificationTypeEnum[keyof typeof RefundWebhookNotificationNotificationTypeEnum];


/**
 * Check if a given object implements the RefundWebhookNotification interface.
 */
export function instanceOfRefundWebhookNotification(value: object): value is RefundWebhookNotification {
    if (!('notificationId' in value) || value['notificationId'] === undefined) return false;
    if (!('notificationType' in value) || value['notificationType'] === undefined) return false;
    if (value['notificationType'] !== 'refund') return false;
    
    if (!('notificationDate' in value) || value['notificationDate'] === undefined) return false;
    if (!('paymentId' in value) || value['paymentId'] === undefined) return false;
    if (!('refund' in value) || value['refund'] === undefined) return false;
    return true;
}

export function RefundWebhookNotificationFromJSON(json: any): RefundWebhookNotification {
    return RefundWebhookNotificationFromJSONTyped(json, false);
}

export function RefundWebhookNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundWebhookNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'notificationId': json['notificationId'],
        'notificationType': json['notificationType'],
        'notificationDate': (json['notificationDate'] == null ? json['notificationDate'] : parseDateTime(json['notificationDate'])),
        'paymentId': json['paymentId'],
        'refund': FinalRefundFromJSON(json['refund']),
    };
}

export function RefundWebhookNotificationToJSON(json: any): RefundWebhookNotification {
    return RefundWebhookNotificationToJSONTyped(json, false);
}

export function RefundWebhookNotificationToJSONTyped(value?: RefundWebhookNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notificationId': value['notificationId'],
        'notificationType': value['notificationType'],
        'notificationDate': value['notificationDate'] == null ? value['notificationDate'] : serializeDateTime(value['notificationDate']),
        'paymentId': value['paymentId'],
        'refund': FinalRefundToJSON(value['refund']),
    };
}

