/* tslint:disable */
/* eslint-disable */
/**
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TpayDeviceData
 */
export interface TpayDeviceData {
    /**
     * 
     */
    platformType: TpayDeviceDataPlatformTypeEnum;
    /**
     * 
     */
    os: string;
    /**
     * 
     */
    browser: string;
    /**
     * 
     */
    language?: string;
    /**
     * 
     */
    timezoneName?: string;
    /**
     * 
     */
    userAgent?: string;
}


/**
 * @export
 */
export const TpayDeviceDataPlatformTypeEnum = {
    Mobile: 'mobile',
    Desktop: 'desktop',
} as const;
export type TpayDeviceDataPlatformTypeEnum = typeof TpayDeviceDataPlatformTypeEnum[keyof typeof TpayDeviceDataPlatformTypeEnum];


/**
 * Check if a given object implements the TpayDeviceData interface.
 */
export function instanceOfTpayDeviceData(value: object): value is TpayDeviceData {
    if (!('platformType' in value) || value['platformType'] === undefined) return false;
    if (!('os' in value) || value['os'] === undefined) return false;
    if (!('browser' in value) || value['browser'] === undefined) return false;
    return true;
}

export function TpayDeviceDataFromJSON(json: any): TpayDeviceData {
    return TpayDeviceDataFromJSONTyped(json, false);
}

export function TpayDeviceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TpayDeviceData {
    if (json == null) {
        return json;
    }
    return {
        
        'platformType': json['platformType'],
        'os': json['os'],
        'browser': json['browser'],
        'language': json['language'] == null ? undefined : json['language'],
        'timezoneName': json['timezoneName'] == null ? undefined : json['timezoneName'],
        'userAgent': json['userAgent'] == null ? undefined : json['userAgent'],
    };
}

export function TpayDeviceDataToJSON(json: any): TpayDeviceData {
    return TpayDeviceDataToJSONTyped(json, false);
}

export function TpayDeviceDataToJSONTyped(value?: TpayDeviceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'platformType': value['platformType'],
        'os': value['os'],
        'browser': value['browser'],
        'language': value['language'],
        'timezoneName': value['timezoneName'],
        'userAgent': value['userAgent'],
    };
}

